// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFKhUeVgR997P8u5-1e28dSiwUXl3Ln-Q',
    appId: '1:1009119556249:web:7ce39a6f837886d51f3e08',
    messagingSenderId: '1009119556249',
    projectId: 'aichatbot-e5ade',
    authDomain: 'aichatbot-e5ade.firebaseapp.com',
    storageBucket: 'aichatbot-e5ade.firebasestorage.app',
    measurementId: 'G-JX13RSEFZX',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDorE7WRppvg08eMWwb5cSmbgeC4ZMKZ_4',
    appId: '1:1009119556249:ios:33ee12ab8f2d18a71f3e08',
    messagingSenderId: '1009119556249',
    projectId: 'aichatbot-e5ade',
    storageBucket: 'aichatbot-e5ade.firebasestorage.app',
    iosBundleId: 'com.akshat.aiChatbot',
  );
}
